### PR TITLE
17.x updates

### PR DESCRIPTION
**Pull request by JedMeister**
A couple of v17.x updates for the outstanding builds.

### CODE REVIEW

**Comment by JedMeister** [comment]
@OnGle @Christie018

TBH, it's almost not worth getting you 2 to look at this as there isn't really much to review here (renamed an empty file and added a new empty file). But hey, in the interests of transparency and ensuring that even simple things aren't overlooked (plus I thought that Mattie might be interested to see this and could be a good opportunity to ask any questions).

**Review by Christie018 — APPROVED** [review]
Approved minor changes, I would like to know what the renamed files functionality is so I am able to use it if needed going forward.

**Comment by OnGle** [comment]
> Approved minor changes, I would like to know what the renamed files functionality is so I am able to use it if needed going forward.

I believe the rename is in relation to https://github.com/turnkeylinux/tracker/issues/1648

**Review by OnGle — APPROVED** [review]
lgtm

**Comment by JedMeister** [comment]
Thanks @Christie018 & @OnGle.

FWIW Mattie, Stefan was on the money! The rename is because the `concrete5` appliance has been renamed `concrete-cms`.

**Pull request merged**
